[package]
name = "new_terra"
version = "0.1.0"
authors = ["Robert Koeninger <rkoeninger@att.net>"]

[[bin]]
name = "new_terra"

[dependencies]
piston = "0.33.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.39.0"
piston2d-opengl_graphics = "0.46.0"
image = "*"
